@startuml
'https://plantuml.com/sequence-diagram

participant Client
participant AuthController
participant AuthService
participant UserRepository
autonumber
== 로그인 플로우 시작 ==

Client -[#red]> AuthController: POST /api/v1/auth/signup
note over Client, AuthController
    LoginRequest
    request body:
    {
        "id" : String
        "password" : String
    }
end note
AuthController -> AuthService: login(LoginRequest)
AuthService -> AuthService: validateUser(id, password)
AuthService -> UserRepository: findUserById(id)
UserRepository -> AuthService: User
AuthService -> AuthService: isMatchesPassword(User.getID(), password)
AuthService -> Client: 일치하지 않으면 예외 메시지 전달
note over AuthService, Client
    ErrorResponse
    response body:
    {
        "resultCode" : String
        "resultData" : String
    }
end note


AuthService-> AuthService: createToken()
AuthService->RedisTemplate: setRefreshToken(refreshToken, refresh_valid_time)
AuthService->AuthController: TokenResponse(accessToken, refreshToken, access_valid_time, refresh_valid_time)
AuthController -[#blue]> Client: TokenResponse
@enduml
